Support for multiple tinci config sections

diff --git a/hooks/post-receive b/hooks/post-receive
--- a/hooks/post-receive
+++ b/hooks/post-receive
@@ -1,34 +1,36 @@
 #!/bin/sh
-TINCIV=1.3.2
-
-MATCH=$(git config --get tinci.match)
-[ -n "$MATCH" ] || MATCH=$(git config --get tinci.branch)
-[ -n "$MATCH" ] || MATCH=master
+TINCIV=2.0.0
 
 while read OLDSHA NEWSHA REF ; do
 
 [ "$NEWSHA" = "0000000000000000000000000000000000000000" ] && continue
+
+for SECTION in $(git config -l | grep -o '^tinci\(\.[^=]*\)*\.' | sed 's/\.$//' | uniq) ; do
+
+MATCH="$(git config --get $SECTION.match)"
+
 SHORTREF=$(echo "$REF" | grep -o "[^/]*$")
-echo "$SHORTREF" | grep -qP "^($MATCH)$" || continue
+echo "$SHORTREF" | grep -qE "^($MATCH)$" || continue
 INPUT="$OLDSHA $NEWSHA $REF"
 
-CMD=$(git config --get tinci.runner)
-SUCCESS=hooks/tinci-success
-FAIL=hooks/tinci-fail
-HOOK=hooks/tinci
+CMD="$(git config --get $SECTION.runner)"
+[ ! "$CMD" ] && CMD="echo"
+SUCCESS="hooks/$SECTION-success"
+FAIL="hooks/$SECTION-fail"
+HOOK="hooks/$SECTION"
 WORK=.tinci
-mkdir -p $WORK
+mkdir -p "$WORK"
 PLOGFILE=$(ls -1t $WORK/*.log 2>/dev/null | head -n1)
 PSTAT=$(tail -n1 "$PLOGFILE" 2>/dev/null | sed -nE 's/^# code ([0-9]+)$/\1/p')
 [ -n "$PSTAT" ] || PSTAT=0
 DIR=$WORK/job.$(od -A n -t d -N 2 /dev/urandom | tr -d ' ')
-mkdir -p $DIR
+mkdir -p "$DIR"
 git archive "$NEWSHA" | tar -x -C "$DIR"
-cd $DIR
-LOGFILE=../$NEWSHA.log
-echo "# tinci $TINCIV\n# ref $REF\n# running $CMD" | tee $LOGFILE
-{ eval "$CMD" 2>&1; echo "# code $?"; } | tee -a $LOGFILE
-STAT=$(tail -n1 $LOGFILE | sed -nE 's/^# code ([0-9]+)$/\1/p')
+cd "$DIR"
+LOGFILE="../$NEWSHA.log"
+echo "# tinci $TINCIV\n# ref $REF\n# running $CMD" | tee "$LOGFILE"
+{ eval "$CMD" 2>&1; echo "# code $?"; } | tee -a "$LOGFILE"
+STAT=$(tail -n1 "$LOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')
 cd ../..
 if [ $STAT -eq 0 ];then
   [ $PSTAT -eq 0 ] && echo "\nJob successful!" || echo "\nJob fixed!"
@@ -41,8 +43,9 @@ else
 fi
 [ -f "$HOOK" ] && \
   echo $INPUT | exec "$HOOK" "$DIR" "$STAT" "$PSTAT" 2>&1
-[ -f "$HOOK-$SHORTREF" ] && \
-  echo $INPUT | exec "$HOOK-$SHORTREF" "$DIR" "$STAT" "$PSTAT" 2>&1
-rm -rf $DIR
+rm -rf "$DIR"
+break
+
+done
 
 done
