Doesn't generate log or checkout a working copy if no runner command is found in config

diff --git a/hooks/post-receive b/hooks/post-receive
--- a/hooks/post-receive
+++ b/hooks/post-receive
@@ -1,5 +1,5 @@
 #!/bin/sh
-TINCIV=2.0.0
+TINCIV=2.1.0
 
 while read OLDSHA NEWSHA REF ; do
 
@@ -13,36 +13,37 @@ SHORTREF=$(echo "$REF" | grep -o "[^/]*$")
 echo "$SHORTREF" | grep -qE "^($MATCH)$" || continue
 INPUT="$OLDSHA $NEWSHA $REF"
 
-CMD="$(git config --get $SECTION.runner)"
-[ ! "$CMD" ] && CMD="echo"
-SUCCESS="hooks/$SECTION-success"
-FAIL="hooks/$SECTION-fail"
 HOOK="hooks/$SECTION"
-WORK=.tinci
-mkdir -p "$WORK"
-PLOGFILE=$(ls -1t $WORK/*.log 2>/dev/null | head -n1)
-PSTAT=$(tail -n1 "$PLOGFILE" 2>/dev/null | sed -nE 's/^# code ([0-9]+)$/\1/p')
-[ -n "$PSTAT" ] || PSTAT=0
-DIR=$WORK/job.$(od -A n -t d -N 2 /dev/urandom | tr -d ' ')
-mkdir -p "$DIR"
-git archive "$NEWSHA" | tar -x -C "$DIR"
-cd "$DIR"
-LOGFILE="../$NEWSHA.log"
-echo "# tinci $TINCIV\n# ref $REF\n# running $CMD" | tee "$LOGFILE"
-{ eval "$CMD" 2>&1; echo "# code $?"; } | tee -a "$LOGFILE"
-STAT=$(tail -n1 "$LOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')
-cd ../..
-if [ $STAT -eq 0 ];then
-  [ $PSTAT -eq 0 ] && echo "\nJob successful!" || echo "\nJob fixed!"
-  [ -f "$SUCCESS" ] && \
-    echo $INPUT | exec "$SUCCESS" "$DIR" "$STAT" "$PSTAT" 2>&1
-else
-  [ $PSTAT -eq 0 ] && echo >&2 "\nJob failed!" || echo >&2 "\nJob is still failing!"
-  [ -f "$FAIL" ] && \
-    echo $INPUT | exec "$FAIL" "$DIR" "$STAT" "$PSTAT" 2>&1
+CMD="$(git config --get $SECTION.runner)"
+if [ "$CMD" ]; then
+  SUCCESS="$HOOK-success"
+  FAIL="$HOOK-fail"
+  WORK=.tinci
+  mkdir -p "$WORK"
+  PLOGFILE=$(ls -1t $WORK/*.log 2>/dev/null | head -n1)
+  PSTAT=$(tail -n1 "$PLOGFILE" 2>/dev/null | sed -nE 's/^# code ([0-9]+)$/\1/p')
+  [ ! "$PSTAT" ] && PSTAT=0
+  DIR=$WORK/job.$(od -A n -t d -N 2 /dev/urandom | tr -d ' ')
+  mkdir -p "$DIR"
+  git archive "$NEWSHA" | tar -x -C "$DIR"
+  cd "$DIR"
+  LOGFILE="../$NEWSHA.log"
+  echo "# tinci $TINCIV\n# ref $REF\n# running $CMD" | tee "$LOGFILE"
+  { eval "$CMD" 2>&1; echo "# code $?"; } | tee -a "$LOGFILE"
+  STAT=$(tail -n1 "$LOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')
+  cd ../..
+  if [ $STAT -eq 0 ];then
+    [ $PSTAT -eq 0 ] && echo "\nJob successful!" || echo "\nJob fixed!"
+    [ -f "$SUCCESS" ] && \
+      echo $INPUT | exec "$SUCCESS" "$DIR" "$STAT" "$PSTAT" 2>&1
+  else
+    [ $PSTAT -eq 0 ] && echo >&2 "\nJob failed!" || echo >&2 "\nJob is still failing!"
+    [ -f "$FAIL" ] && \
+      echo $INPUT | exec "$FAIL" "$DIR" "$STAT" "$PSTAT" 2>&1
+  fi
 fi
 [ -f "$HOOK" ] && \
-  echo $INPUT | exec "$HOOK" "$DIR" "$STAT" "$PSTAT" 2>&1
+  echo $INPUT | exec "$HOOK" "$DIR" $STAT $PSTAT 2>&1
 rm -rf "$DIR"
 break
 
