Shellcheck linting

diff --git a/hooks/post-receive b/hooks/post-receive
--- a/hooks/post-receive
+++ b/hooks/post-receive
@@ -1,5 +1,7 @@
-#!/bin/bash
-TINCIV=6.1.0
+#!/bin/sh
+TINCIV=7.0.0
+
+set -e
 
 HOOK="$(pwd)/hooks/tinci"
 PREHOOK="$(pwd)/hooks/tinci-pre"
@@ -7,32 +9,32 @@ LOGDIR="$(pwd)/.tinci"
 mkdir -p "$LOGDIR"
 
 TDIR=$(mktemp -d "${TMPDIR:-/tmp}"/tinci.XXXXXXXX)
-mkdir -p $TDIR
+mkdir -p "$TDIR"
 trap "trap - EXIT; rm -rf $TDIR" EXIT
 
-while read OLDSHA NEWSHA REF ; do
+while read -r OLDSHA NEWSHA REF ; do
 
   [ "$NEWSHA" != "0000000000000000000000000000000000000000" ] || continue
 
-  CMD="$(git archive $NEWSHA | tar -t | grep '^.tinci$')"
+  CMD="$(git archive "$NEWSHA" | tar -t | grep '^.tinci$')"
   [ "$CMD" ] || continue
 
   INPUT="$OLDSHA $NEWSHA $REF"
   LOGFILE="$LOGDIR/$NEWSHA.log"
   PLOGFILE="$LOGDIR/$OLDSHA.log"
   WDIR=$TDIR/$NEWSHA
-  mkdir -p $WDIR
+  mkdir -p "$WDIR"
 
-  git archive $NEWSHA | tar -x -C $WDIR
+  git archive "$NEWSHA" | tar -x -C "$WDIR"
   [ -x "$WDIR/$CMD" ] || continue
 
-  [ -f $PLOGFILE ] && PSTAT=$(tail -n1 $PLOGFILE | sed -nE 's/^# code ([0-9]+)$/\1/p')
+  [ -f "$PLOGFILE" ] && PSTAT=$(tail -n1 "$PLOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')
   [ ! "$PSTAT" ] && PSTAT=0
 
-  [ -x "$PREHOOK" ] && echo $INPUT | ./"$PREHOOK" $PSTAT $WDIR 2>&1
+  [ -x "$PREHOOK" ] && echo "$INPUT" | ./"$PREHOOK" $PSTAT "$WDIR" 2>&1
 
-  ( cd $WDIR
-    echo -e "# tinci $TINCIV\n# ref $REF\n# running: ./$CMD"
+  ( cd "$WDIR" || exit 1
+    printf %s "# tinci $TINCIV\\n# ref $REF\\n# running: ./$CMD"
     ./"$CMD" 2>&1
     echo "# code $?"
   ) | tee "$LOGFILE"
@@ -40,11 +42,11 @@ while read OLDSHA NEWSHA REF ; do
   STAT=$(tail -n1 "$LOGFILE" | sed -nE 's/^# code ([0-9]+)$/\1/p')
   [ ! "$STAT" ] && STAT=-1
 
-  [ -x "$HOOK" ] && echo $INPUT | ./"$HOOK" $STAT $WDIR 2>&1
+  [ -x "$HOOK" ] && echo "$INPUT" | ./"$HOOK" $STAT "$WDIR" 2>&1
 
   if [ $STAT -eq 0 ]; then
-    [ $PSTAT -eq 0 ] && echo -e "\nJob successful!" || echo -e "\nJob fixed!"
+    [ $PSTAT -eq 0 ] && printf \\n%s "Job successful!" || printf \\n%s "Job fixed!"
   else
-    [ $PSTAT -eq 0 ] && echo -e >&2 "\nJob failed!" || echo -e >&2 "\nJob is still failing!"
+    [ $PSTAT -eq 0 ] && printf \\n%s "Job failed!" >&2 || printf \\n%s "Job is still failing!" >&2
   fi
 done
