Changed tinci-success and tinci-fail hooks to take previous-job-revision, current-job-revision, current-job-refspec, previous-job-status as arguments

diff --git a/hooks/tinci b/hooks/tinci
--- a/hooks/tinci
+++ b/hooks/tinci
@@ -1,5 +1,5 @@
 #!/bin/sh
-VERSION=0.0.3
+VERSION=0.1.0
 
 BRANCH=$(git config --get tinci.branch)
 [ -n "$BRANCH" ] || BRANCH=master
@@ -15,19 +15,22 @@ FAIL=hooks/tinci-fail
 DIR=job.$RANDOM
 mkdir -p .tinci
 cd .tinci
-PREVSTAT=$(tail -n1 `ls -1t | head -n1`)
-[ -n "$PREVSTAT" ] || PREVSTAT=0
+PLOGFILE=$(ls -1t | head -n1)
+PREV=$(echo $PLOGFILE | cut -d '.' -f 1)
+PSTAT=$(tail -n1 $PLOGFILE)
+[ -n "$PSTAT" ] || PSTAT=0
 git clone .. -b "$BRANCH" $DIR > /dev/null
 cd $DIR
-LOGFILE=../$(git rev-parse HEAD).log
+REV=$(git rev-parse HEAD)
+LOGFILE=../$REV.log
 echo "=== tinci (v$VERSION) is running '$CMD' ===" | tee $LOGFILE
 { eval "$CMD" 2>&1; echo "Job exited with code:\n$?"; } | tee -a $LOGFILE
 if [ $(tail -n1 $LOGFILE) -eq 0 ];then
-  [ $PREVSTAT -eq 0 ] && echo "Job successful!" || echo "Job fixed!"
-  (cd ../..; [ -f "$SUCCESS" ] && echo "$INPUT" | exec "$SUCCESS" $PREVSTATE 2>&1)
+  [ $PSTAT -eq 0 ] && echo "Job successful!" || echo "Job fixed!"
+  (cd ../..; [ -f "$SUCCESS" ] && exec "$SUCCESS" $PREV $REV $REF $PSTAT 2>&1)
 else
-  [ $PREVSTAT -eq 0 ] && echo >&2 "Job failed!" || echo >&2 "Job is still failing!"
-  (cd ../..; [ -f "$FAIL" ] && echo "$INPUT" | exec "$FAIL" $PREVSTAT 2>&1)
+  [ $PSTAT -eq 0 ] && echo >&2 "Job failed!" || echo >&2 "Job is still failing!"
+  (cd ../..; [ -f "$FAIL" ] && exec "$FAIL" $PREV $REV $REF $PSTAT 2>&1)
 fi
 cd ..
 rm -rf $DIR
